
#spring:
#  jpa.hibernate.ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/exl?serverTimezone=UTC
#    username: user
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    
#spring:
#  jpa.database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
  
    